---
- name: Desplegar LAMP
  hosts: target2
  vars:
   - http_port: 80
   - webserver_hostname: miservidor.local
   - webserver_admin: perico@miservidor.local
  tasks:
   - name: instalar software
     apt: name={{ item }} state=present
     loop: 
      - apache2
      - mysql-server
      - libapache2-mod-php

   - name: Establecer el servername
     lineinfile: 
        regexp: ".*ServerName.*"
        line: "          ServerName  {{ webserver_hostname }} "
        state: present
        path: /etc/apache2/sites-enabled/000-default.conf
     notify: reiniciar apache

   - name: Establecer el serveradmin
     lineinfile:
        regexp: ".*ServerAdmin.*"
        line: "          ServerAdmin  {{ webserver_admin }} "
        state: present
        path: /etc/apache2/sites-enabled/000-default.conf
     notify: reiniciar apache

  handlers:
   - name: reiniciar apache
     service: name=apache2 state=restarted
