---
- name: Desplegar LAMP
  hosts: target2
  vars:
   - http_port: 80
   - webserver_hostname: miservidor
  tasks:
   - name: instalar apache2
     apt: name=apache2 state=present

   - name: instalar mysql
     apt: name=mysql-server state=present


